### ISSUE TITLE
rename extension.RegisteredFuncs

### ISSUE THREAD

**Issue by ryancurrah** [jaimeteb/chatto#20]
I think it would be clearer to rename `extension.RegisteredFuncs` to `extension.RegisteredCommands` or `extension.RegisteredCommandFuncs`. 

This would make it more inline with the wording used throughout the bot.

**Comment by jaimeteb** [comment]
Yeah, `extension.RegisteredCommandFuncs` is more explicative I think.

**Comment by ryancurrah** [comment]
I agree
