### ISSUE TITLE
make chatto kubernetes friendly

### ISSUE THREAD

**Issue by ryancurrah** [jaimeteb/chatto#35]
There are a few nice things that we can add to make the chatto server friendly for Kubernetes usage.

1. Use a prefix for env variables `CHATTO_BOT` and `CHATTO_CHN`. [x]
2. Hot reload when configuration changes. [x]
3. Provide an example deployment YAML. [x]
4. Add a liveness/health check endpoint that does not require auth to the bot. [x]

**Comment by ryancurrah** [comment]
I will try to get this one done on the weekend.

**Comment by jaimeteb** [comment]
Fantastic. I love kubertetes, and these would definitely help.

I was thinking the same thing, the should be a health check endpoint. And the example deployment could be added to the documentation along with docker a d docker compose.
