### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by msidana** [jaimeteb/chatto#58]
In examples section of readme file, Pokemon Example link is broken.
It should point to https://github.com/jaimeteb/chatto/tree/master/examples/02_pokemon instead of 
https://github.com/jaimeteb/chatto/tree/master/examples/03_pokemon
PS: 02_pokemon instead of 03_pokemon.

**Comment by jaimeteb** [comment]
@msidana thank you so much ! it's fixed now !
