### ISSUE TITLE
use goreleaser for releases

### ISSUE THREAD

**Issue by ryancurrah** [jaimeteb/chatto#9]
We should use goreleaser for releases. 

The following would probably need to change...
- Change the Dockerfile to work with goreleaser.
- Change Github actions to run gorleaser when a semver tag is created.

**Comment by jaimeteb** [comment]
Of course, and as you said on #7, goreleaser can be used in GitHub Actions, so goreleaser can build the Docker image right?

**Comment by ryancurrah** [comment]
Yeah. I will work on this one.
